name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  # Review gh actions docs if you want to further define triggers, paths, etc
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          cache: npm

      - name: Install dependencies
        run: npm ci

      - run: npm run build -w @react-shader/renderer

      - run: npm run build -w @react-shader/stdlib

      - run: npm run build -w @react-shader/fiber

      - name: Build website
        run: npm run build -w @react-shader/docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./packages/docs/out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2